model:
  features_extractor:
    latent_dim: 2048
    weights: "path/to/best_features_extractor.pt"
  classifier:
    n_classes: 4
    weights: "path/to/best_classifier.pt"

dataset:
  name: "rxrx1"
  download: False

hyper_parameters:
  batch_size: 128
  num_workers: 8
