model:
  features_extractor:
    latent_dim: 2048
    weights: "path/to/best_features_extractor.pt"
  classifier:
    n_classes: 4
    weights: null
    save_path: "path/to/best_classifier.pt"

dataset:
  name: "rxrx1"
  download: False
  split: "train"
  fraction: 1.0

hyper_parameters:
  batch_size: 16
  num_workers: 16

  learning_rate: 0.001
  weight_decay: 0.0001


  step_size: 3
  gamma: 0.1

  num_epochs: 20
