model:
  features_extractor:
    latent_dim: 2048
    weights: "default"
    save_path: "path/to/best_features_extractor.pt"
  project_head:
    latent_dim: 2048
    projection_dim: 128

dataset:
  name: "rxrx1"
  download: False

data_augmentation:
  size: 256
  scaler: 1
  kernel_size: 3

hyper_parameters:
  batch_size: 16
  num_workers: 16

  learning_rate: 0.0003
  weight_decay: 0.0001

  eta_min: 0
  last_epoch: -1

  num_epochs: 100
