model:
  features_extractor:
    latent_dim: 2048
    weights: "default"
    save_path: "path/to/best_features_extractor.pt"
  project_head:
    latent_dim: 2048
    projection_dim: 128

dataset:
  name: "rxrx1"
  download: False
  split: "train"
  fraction: 1.0

data_augmentation:
  general:
    size: 256
  sam_erasing:
    sam:
      vit_type: "vit_b"
      weights: "path/to/best_sam.pth"
      mask_mode: "generator"
      points_per_side: 16
      points_per_batch: 64
      pred_iou_thresh: 0.9
      box_nms_thresh: 0.9
      crop_nms_thresh: 0.9
      min_mask_region_area: 5
    mask_mode: "keep"
    scale: [0.3, 0.3, 0.5, 0.5]
    kernel_size: [16, 16]
    thresh: 10
    min_area: 2000
    percentage: 1
  rotation:
    degrees: 90
  color_jitter:
    scaler: 1
    probability: 0.8
  gaussian_blur:
    kernel_size: 3
    probability: 0.5
  grayscale:
    probability: 0.2

hyper_parameters:
  temperature: 0.2

  batch_size: 8
  num_workers: 8

  learning_rate: 0.002
  weight_decay: 0.00001

  eta_min: 0
  last_epoch: -1

  num_epochs: 100

  gradient_accumulation: 32
